version: '3.1'

services:

  wordpress:
    image: wordpress:5.1.1-php7.1-apache
    ports:
      - 8000:80
    volumes:
      - ./wordpress/plugins:/var/www/html/wp-content/plugins
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: '12345'
      WORDPRESS_DB_NAME: blog
    links:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: '12345'

  ticketmaster:
    image: node:10-slim
    volumes:
      - ./ticketmaster:/app
    working_dir: /app
    ports:
      - 3001:3000
    command:
      - yarn
      - dev
    environment:
      PORT: 3000

  proxy:
    restart: always
    build: ./nova-proxy
    links:
      - wordpress
    ports:
      - 8080:8080
    environment:
      HYPERNOVA_BATCH: http://ticketmaster:3000/batch
